export const normalizeClubFromTooltip = (raw) => ({
    id: raw.id ?? null,
    name: raw.club_name ?? null,
    nick: raw.club_nick ?? null,
    country: raw.country ?? null,
    division: raw.division ?? null,
    group: raw.group ?? null,
    manager_name: raw.manager_name ?? null,
    fanclub: raw.fanclub ?? null,
    stadium: raw.stadium ?? null,
    city: raw.city ?? null,
    a_team: raw.a_team ?? null,
    b_team: raw.b_team ?? null,
    created: raw.created ?? null,
    is_diamond: raw.is_diamond ?? null,
    cash: raw.cash ?? null,
    online: raw.online ?? null,
});

export const normalizeClubFromScoutReport = (raw) => ({
    id: raw.club ?? null,
    name: raw.klubnavn ?? null,
    nick: null,
    country: raw.land ?? null,
    division: raw.division ?? null,
    group: raw.pulje ?? null,
    manager_name: null,
    fanclub: null,
    stadium: null,
    city: null,
    a_team: null,
    b_team: null,
    created: null,
    is_diamond: null,
    cash: raw.cash ?? null,
    online: raw.online ?? null,
});
