#!/usr/bin/env node
/**
 * build.js -- TM Scripts bundle builder (esbuild)
 *
 * Bundles all page entry points from src/pages/ into dist/tm-bundle.js.
 *
 * Usage:
 *   node build.js           -- build once (GitHub URL)
 *   node build.js --local   -- build with file:// URL (local testing)
 *   node build.js --watch   -- rebuild on any src/ change
 */

'use strict';

const fs      = require('fs');
const path    = require('path');
const esbuild = require('esbuild');

const ROOT = __dirname;
const SRC  = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');

const isLocal = process.argv.includes('--local');
const isWatch = process.argv.includes('--watch');

// --- Page entry points -------------------------------------------------------
const PAGES = [
    'transfer',
    'match',
    'player',
    'players',
    'squad',
    'league',
    'stats',
    'history',
    'shortlist',
    'import',
    'r5history',
    'dbinspect',
    'dbrepair',
];

// --- Build -------------------------------------------------------------------

async function buildAll() {
    if (!fs.existsSync(DIST)) fs.mkdirSync(DIST, { recursive: true });

    // Generate a virtual entry point that imports all pages
    const entryContent = PAGES.map(p => `import './pages/${p}.js';`).join('\n') + '\n';
    const entryFile = path.join(SRC, '_main.js');
    fs.writeFileSync(entryFile, entryContent, 'utf8');

    try {
        const result = await esbuild.build({
            entryPoints: [entryFile],
            bundle: true,
            outfile: path.join(DIST, 'tm-bundle.js'),
            format: 'iife',
            platform: 'browser',
            target: 'es2018',
            logLevel: 'warning',
        });

        const stat = fs.statSync(path.join(DIST, 'tm-bundle.js'));
        const kb = (stat.size / 1024).toFixed(1);
        console.log('[build] OK  dist/tm-bundle.js  (' + kb + ' KB, ' + PAGES.length + ' pages)');

        if (result.errors.length) {
            console.error('[build] Errors:', result.errors);
        }
    } finally {
        if (fs.existsSync(entryFile)) fs.unlinkSync(entryFile);
    }

    generateMainStub();
}

function generateMainStub() {
    const BASE = isLocal
        ? 'file://H:/projects/Moji/tmscripts'
        : 'https://raw.githubusercontent.com/somi93/tm-script/main';

    const lines = [
        '// ==UserScript==',
        '// @name         TM Scripts',
        '// @namespace    https://trophymanager.com',
        '// @version      2.0.0',
        '// @description  TrophyManager enhancement suite',
        '// @match        https://trophymanager.com/*',
        '// @require      ' + BASE + '/dist/tm-bundle.js',
        '// @grant        none',
        '// @run-at       document-end',
        '// ==/UserScript==',
        '',
        '// Auto-generated by build.js -- do not edit manually.',
        '// Run `node build.js` to rebuild.',
    ];
    if (isLocal) {
        lines.push('// NOTE: using local file:// URL -- do not commit!');
    }

    fs.writeFileSync(path.join(ROOT, 'tm.user.js'), lines.join('\n'), 'utf8');
    const mode = isLocal ? 'LOCAL (file://)' : 'GITHUB';
    console.log('[build] OK  tm.user.js  (' + mode + ')');
}

// --- Watch mode --------------------------------------------------------------

if (isWatch) {
    buildAll();
    console.log('[build] Watching for changes...  (Ctrl+C to stop)');

    let debounceTimer = null;
    const rebuild = (filename) => {
        if (debounceTimer) clearTimeout(debounceTimer);
        debounceTimer = setTimeout(() => {
            console.log('[build] Changed: ' + (filename || '?'));
            buildAll();
        }, 150);
    };

    const watchDirs = [
        path.join(SRC, 'lib'),
        path.join(SRC, 'components'),
        path.join(SRC, 'pages'),
    ];
    for (const dir of watchDirs) {
        fs.watch(dir, { recursive: true }, (_, f) => {
            if (f && f.endsWith('.js')) rebuild(f);
        });
    }
} else {
    buildAll().catch(e => {
        console.error('[build] Fatal error:', e.message);
        process.exit(1);
    });
}
