// ==UserScript==
// @name         TM Scripts
// @namespace    https://trophymanager.com
// @version      2.0.2799.1777115269554
// @description  TrophyManager enhancement suite
// @match        https://trophymanager.com/*
// @grant        none
// @run-at       document-start
// @updateURL    file://H:/projects/Moji/tmscripts/tm.user.js
// @downloadURL  file://H:/projects/Moji/tmscripts/tm.user.js
// ==/UserScript==

// Auto-generated by build.js -- do not edit manually.
// Run `node build.js` to rebuild.
// NOTE: using local file:// URL -- do not commit!

(function () {
    'use strict';

    if (window.top !== window.self) return;

    const BUNDLE_URL = "file://H:/projects/Moji/tmscripts/dist/tm-bundle.js?v=3ec69136";
    const PREBOOT_STYLE_ID = 'tmvu-player-preboot-style';

    const isPlayerPage = /^\/players\/\d+\/?$/i.test(window.location.pathname);
    const root = document.documentElement;
    if (!root) return;

    const removePlayerPreboot = () => {
        root.classList.remove('tmvu-player-preboot');
        delete root.dataset.tmvuPlayerPreboot;
        const style = document.getElementById(PREBOOT_STYLE_ID);
        if (style) style.remove();
    };

    if (isPlayerPage && root.dataset.tmvuPlayerPreboot !== "1") {
        root.dataset.tmvuPlayerPreboot = "1";
        root.classList.add('tmvu-player-preboot');
        const style = document.createElement("style");
        style.id = PREBOOT_STYLE_ID;
        style.textContent = `
html.tmvu-player-preboot body {
    visibility: hidden !important;
}
`;
        (document.head || root).appendChild(style);
    }

    const loadBundle = () => {
        if (root.dataset.tmvuBundleRequested === "1") return;
        root.dataset.tmvuBundleRequested = "1";
        const script = document.createElement("script");
        script.src = BUNDLE_URL;
        script.async = false;
        script.onload = () => {
            root.dataset.tmvuBundleLoaded = "1";
        };
        script.onerror = () => {
            console.error("[TM Scripts] Failed to load bundle", BUNDLE_URL);
            removePlayerPreboot();
        };
        (document.head || document.documentElement).appendChild(script);
    };

    window.setTimeout(() => {
        if (root.dataset.tmvuBundleLoaded === "1") return;
        if (root.dataset.tmvuPlayerPreboot === "1") removePlayerPreboot();
    }, 8000);

    if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", loadBundle, { once: true });
    } else {
        loadBundle();
    }
})();