// ==UserScript==
// @name         TM Scripts
// @namespace    https://trophymanager.com
// @version      2.0.0
// @description  TrophyManager enhancement suite
// @match        https://trophymanager.com/*
// @require      https://raw.githubusercontent.com/somi93/tm-script/main/dist/tm-bundle.js
// @grant        none
// @run-at       document-end
// ==/UserScript==

// Auto-generated by build.js -- do not edit manually.
// Run `node build.js` to rebuild.