// ==UserScript==
// @name         TM Scripts
// @namespace    https://trophymanager.com
// @version      2.0.0
// @description  TrophyManager enhancement suite — transfer scanner, match viewer, player tools, squad, league and more
// @match        https://trophymanager.com/*
// @require      file://H:/projects/Moji/tmscripts/dist/tm-libs.js
// @require      file://H:/projects/Moji/tmscripts/dist/pages/tm-transfer.js
// @require      file://H:/projects/Moji/tmscripts/dist/pages/tm-match.js
// @require      file://H:/projects/Moji/tmscripts/dist/pages/tm-player.js
// @require      file://H:/projects/Moji/tmscripts/dist/pages/tm-players.js
// @require      file://H:/projects/Moji/tmscripts/dist/pages/tm-squad.js
// @require      file://H:/projects/Moji/tmscripts/dist/pages/tm-league.js
// @require      file://H:/projects/Moji/tmscripts/dist/pages/tm-stats.js
// @require      file://H:/projects/Moji/tmscripts/dist/pages/tm-history.js
// @require      file://H:/projects/Moji/tmscripts/dist/pages/tm-shortlist.js
// @require      file://H:/projects/Moji/tmscripts/dist/pages/tm-import.js
// @require      file://H:/projects/Moji/tmscripts/dist/pages/tm-r5history.js
// @require      file://H:/projects/Moji/tmscripts/dist/pages/tm-dbinspect.js
// @require      file://H:/projects/Moji/tmscripts/dist/pages/tm-dbrepair.js
// @grant        none
// @run-at       document-end
// ==/UserScript==

// Auto-generated by build.js — do not edit manually.
// Run `node build.js` to rebuild bundles and regenerate this file.