// ==UserScript==
// @name         TM — tm-stats
// @namespace    https://trophymanager.com
// @version      2.0.0
// @match        https://trophymanager.com/matches/stats/*
// @require      file://H:/projects/Moji/tmscripts/dist/tm-libs.js
// @require      file://H:/projects/Moji/tmscripts/dist/pages/tm-stats.js
// @grant        none
// @run-at       document-end
// ==/UserScript==

// Auto-generated by build.js — do not edit manually.